### ISSUE TITLE
Feature request: Nordic UART/BBC micro:bit support

### ISSUE THREAD

**Issue by jaustin** [loginov-rocks/Web-Bluetooth-Terminal#11]
Hello,
the BBC micro:bit (microbit.org) uses the Nordic UART service https://lancaster-university.github.io/microbit-docs/ble/uart-service/ - it would be awesome if this app supported micro:bit. This would also allow trivial support for other Arm MBED boards https://os.mbed.com/teams/Bluetooth-Low-Energy/wiki/UART-access-over-BLE

There's a program for testing with the micro:bit here https://makecode.microbit.org/_8gyHC3Aq8Yxu

**Comment by 1oginov** [comment]
Hello @jaustin !

What service & characteristic UUIDs does microbit use? Could it be configured to the custom UUIDs?

**Comment by 1oginov** [comment]
You can also try different samples from Google https://googlechrome.github.io/samples/web-bluetooth/ to find what missing.
