### ISSUE TITLE
your github.io site is down?

### ISSUE THREAD

**Issue by jackdaddy69** [loginov-rocks/Web-Bluetooth-Terminal#12]
I demo your software at your github.io site, but it appears to be down.  Please fix.  JD69

**Comment by loginov-rocks** [comment]
https://loginov-rocks.github.io/Web-Bluetooth-Terminal

**Comment by jackdaddy69** [comment]
Your main page links also need to be changed. :)

**Comment by loginov-rocks** [comment]
@jackdaddy69 of course, I just changed my nickname here
