### ISSUE TITLE
Separators

### ISSUE THREAD

**Issue by jackdaddy69** [loginov-rocks/Web-Bluetooth-Terminal#14]
Could you please change your code to have a binary mode.  I do not think it is reasonable to force separators on the user in many cases.  For example, I have an application with an HM-10 that sends live binary data back and forth to an arduino.  I would prefer not to hack apart your code.  Maybe you could just send all data immediately to the requester like the serialport library using some sort of flag like binarymode or something like that?  This way you could keep your code the way it is for old users, and add a binary mode for people like me :)

I also commented on the issue of your promises chain not working correctly for signalling the end of sends.  Please look into it.

Thank you so much, Jack

**Comment by loginov-rocks** [comment]
Hi @jackdaddy69 ! At the moment I don't have any concerns about binary mode, it can be added to the package. Could you please open an issue in the https://github.com/loginov-rocks/bluetooth-terminal and we'll handle it.
