### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by Puneetkumarpal** [loginov-rocks/Web-Bluetooth-Terminal#18]
Its not working with windows

**Comment by Puneetkumarpal** [comment]
Hello i am using noble in electron to create a windows desktop app which  connect my windows device to connect other hardware (HM10 ble module on another side) i am facing some issues.

first time its works fine, but some times it's disconnect automaticly

now the problems starts once i disconnected the device 

=>it's doesn't connect again to any device.

=>it dose not scan any device.

i don't know where the problem. is in my implementation or in noble

please help  

my code:
<renderer.js>

`var noble = require('noble');

const ECHO_SERVICE_UUID = 'ffe0';
const ECHO_CHARACTERISTIC_UUID = 'ffe1';
var echoCharacteristic = [];
var ble_list = [];

let index = 0;

const deviceNameLabel = document.getElementById('device-name');
const terminalContainer = document.getElementById('terminal');
const inputField = document.getElementById('input');

const defaultDeviceName = 'Terminal';
const terminalAutoScrollingLimit = terminalContainer.offsetHeight / 2;
let isTerminalAutoScrolling = true;
var recive = "";

const scrollElement = (element) => {
    const scrollTop = element.scrollHeight - element.offsetHeight;

    if (scrollTop > 0) {
        element.scrollTop = scrollTop;
    }
};

const logToTerminal = (message, type = '') => {
    terminalContainer.insertAdjacentHTML('beforeend',
        `<div${type && ` class="${type}"`}>${message}</div>`);

    if (isTerminalAutoScrolling) {
        scrollElement(terminalContainer);
    }
};

$("#find").click(function (params) {
    noble.on('stateChange', state => {
        if (state === 'poweredOn') {
            noble.startScanning([ECHO_SERVICE_UUID]);
            console.log('Scanning');
            logToTerminal('Scanning');
        } else {
            noble.stopScanning();
        }
    });

    noble.on('discover', peripheral => {
        // connect to the first peripheral that is scanned

        const name = peripheral.advertisement.localName;
        logToTerminal(`Found '${name}' ${peripheral.id}`);
        console.log(`Found '${name}' ${peripheral.id}`);

        // new implimentation of finding bluetooth device
        if (ble_list.indexOf(peripheral) > -1) {
            index = ble_list.indexOf(peripheral);
        } else {
            ble_list.push(peripheral);
            index = ble_list.indexOf(peripheral);
        }
        $('#ble-list').append('<option value = ' + ble_list.length + '>' + name + '</option>');
    });
})

$("#connect").click(function (params) {
    noble.stopScanning();
    index = ($("#ble-list").val()) - 1;
    deviceNameLabel.textContent = ble_list[index].advertisement.localName ? ble_list[index].advertisement.localName : defaultDeviceName;
    console.log(`Connecting to '${ble_list[index].advertisement.localName}' ${ble_list[index].id}`);
    logToTerminal(`Connecting to '${ble_list[index].advertisement.localName}' ${ble_list[index].id}`);
    connectAndSetUp(ble_list[index]);
})

$("#disconnect").click(function (params) {
    index = ($("#ble-list").val()) - 1;
    echoCharacteristic[index].unsubscribe(error => {
        if (error) {
            console.error('Error unsubscribing to echoCharacteristic');
            logToTerminal('Error unsubscribing to echoCharacteristic');
        } else {
            console.log('unSubscribed for echoCharacteristic notifications');
            logToTerminal('unSubscribed for echoCharacteristic notifications');
            ble_list[index].disconnect(error => {
                if (error) {
                    console.log("Error in disconnect");
                    logToTerminal('disconnected' + error);
                } else {
                    console.log("disconnected");
                    logToTerminal('disconnected');
                }
            });
        }
    });
})


function connectAndSetUp(peripheral) {

    peripheral.connect(error => {
        console.log('Connected to', peripheral.id);
        logToTerminal('Connected to ' + peripheral.id);
        // specify the services and characteristics to discover
        const serviceUUIDs = [ECHO_SERVICE_UUID];
        const characteristicUUIDs = [ECHO_CHARACTERISTIC_UUID];

        peripheral.discoverSomeServicesAndCharacteristics(
            serviceUUIDs,
            characteristicUUIDs,
            onServicesAndCharacteristicsDiscovered
        );

        peripheral.once('disconnect', function () {
            // do something
            console.log("ones disconnected")
        });
    });

    peripheral.on('disconnect', () => {
        ble_list[index].removeAllListeners();
        peripheral.removeAllListeners();
        console.log('disconnected');
    });
}

function onServicesAndCharacteristicsDiscovered(error, services, characteristics) {
    console.log('Discovered services and characteristics');
    logToTerminal('Discovered services and characteristics');
    echoCharacteristic.push(characteristics[0]);

    // data callback receives notifications
    echoCharacteristic[index].on('data', (data, isNotification) => {
        //console.log('Received: "' + data + '"');
        //logToTerminal('Received: "' + data + '"');
        recive += data;

        if (IsJsonString(recive)) {
            console.log(recive)
        }
    });

    // subscribe to be notified whenever the peripheral update the characteristic
    echoCharacteristic[index].subscribe(error => {
        if (error) {
            console.error('Error subscribing to echoCharacteristic');
            logToTerminal('Error subscribing to echoCharacteristic');
        } else {
            console.log('Subscribed for echoCharacteristic notifications');
            logToTerminal('Subscribed for echoCharacteristic notifications');
        }
    });

}

function IsJsonString(str) {
    try {
        JSON.parse(str);
    } catch (e) {
        return false;
    }
    return true;
}

$("#send-form").submit(function (params) {
    // const message = new Buffer('hello, ble ', 'utf-8');
    const message = new Buffer(inputField.value, 'utf-8');
    console.log("Sending:  '" + message + "'");
    logToTerminal("Sending:  '" + message + "'");
    //inputField.value = '';
    inputField.focus();
    echoCharacteristic[index].write(message);

})`


index.html

`<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#2196f3">
    <meta name="msapplication-config" content="browserconfig.xml">
    <meta name="theme-color" content="#2196f3">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="msapplication-starturl" content="./">
    <meta name="description" content="Progressive Web Application for serial communication with your own Bluetooth Low Energy (Smart) devices">

    <title>Web Bluetooth Terminal</title>

    <link rel="manifest" href="manifest.json">
    <link rel="apple-touch-icon" sizes="180x180" href="icons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="icons/favicon-16x16.png">
    <link rel="mask-icon" href="icons/safari-pinned-tab.svg" color="#2196f3">
    <link rel="shortcut icon" href="icons/favicon.ico">

    <link href="https://fonts.googleapis.com/css?family=Roboto+Mono" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="css/normalize.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">

</head>

<body>

    <div class="app">

        <div class="toolbar">

            <div id="device-name" class="name">Terminal</div>

            <select id="ble-list">
                
            </select>
            <div class="buttons">

                <button id="find" type="button" aria-label="Connect">
                    <i class="material-icons">autorenew</i>
                </button>

                <button id="connect" type="button" aria-label="Connect">
                    <i class="material-icons">bluetooth_connected</i>
                </button>

                <button id="disconnect" type="button" aria-label="Disconnect">
                    <i class="material-icons">bluetooth_disabled</i>
                </button>

            </div>

        </div>

        <div id="terminal" class="terminal"></div>

        <form id="send-form" class="send-form" onsubmit="return false;">

            <input id="input" type="text" aria-label="Input" value="GET_BOARD_LOGS" autocomplete="off" placeholder="Type something to send...">

            <button type="submit" aria-label="Send">
                <i class="material-icons">send</i>
            </button>

        </form>

    </div>
    <script>
        window.$ = window.jQuery = require("jquery");
    </script>
    <script src="./renderer.js"></script>
    
    

</body>

</html>`

**Comment by Puneetkumarpal** [comment]
Notification is not working in windows 10 please help me to get notification. by your code data send successfully on peripheral device(HM 10). but not able to get any data back.

**Comment by aRbotics** [comment]
Any progress on Windows fix?   Tests good on several Macs, Samsung Android tablet, Asus Chromebook.  Does not work on Windows 10, iPhone 6 or iPad.  All using current version of Chrome.

**Comment by loginov-rocks** [comment]
Hello @Puneetkumarpal and @aRbotics 

Please check https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md#implementation-status 

There's no support for Electron since it's not a regular browser, but rather a Chromium-based Node.js app.
